logging:
  level:
    org.apache.coyote.http11: DEBUG
    org.apache.tomcat.util.net: DEBUG
    org.springframework.web.socket: DEBUG
    root: INFO
    com.loyalt: DEBUG
    com.loyalt.partner: DEBUG
    org.springframework.web: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.boot.web.embedded.tomcat: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %level - %msg%n"

server:
  port: 8085
  address: 0.0.0.0
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      prefix: access_log
      suffix: .log
      pattern: '%h %l %u %t "%r" %s %b %D ms'
      rotate: true

spring:
  web:
    log-request-details: true
    cors:
      allowed-origins: '*'
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: '*'
      allow-credentials: true
      max-age: 3600
  datasource:
    url: jdbc:postgresql://localhost:5001/loyalty
    username: loyalAdmin
    password: passwordLoyal
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: loyalty-main-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
clickhouse:
  datasource:
    # Обычный HTTP URL, который идеально подходит для Яндекс-драйвера
    url: jdbc:clickhouse://localhost:8123/transactions
    username: admin
    password: password